#!/bin/bash

apt update -y
apt install default-jre -y
apt install awscli -y

#app run with new wwwuser1
useradd -m -d /home/wwwuser1/ wwwuser1
aws s3 cp s3://sbp1/frontend-service/frontend-service-0.0.1-SNAPSHOT.jar /home/wwwuser1 --region eu-central-1
chmod +x /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar

cat <<-'EOF' > "/home/wwwuser1/CRONlook.sh"
#!/bin/bash

LASTUPLOAD=$(aws s3 ls s3://sbp1/frontend-service/frontend-service-0.0.1-SNAPSHOT.jar | grep -o "..:..:")
NOW=$(date "+%d-%m-%Y-%H:%M:%S" -d "1 minute ago" | grep -o "..:..:*")

  if
    [ "$LASTUPLOAD" == "$NOW" ]
  then
    aws s3 cp s3://sbp1/frontend-service/frontend-service-0.0.1-SNAPSHOT.jar /home/wwwuser1 --region eu-central-1
    chmod +x /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar
    echo "there is a new file :)"
    echo "last file loaded"
    echo "service will restart"
    date "+%d-%m-%Y-%H:%M:%S" -d "1 minute ago" > /home/wwwuser1/lastfilelog.txt
    pid=`ps aux | grep frontend-service-0.0.1-SNAPSHOT.jar | awk '{print $2}'`
    kill -9 $pid
    java -jar /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar
  else
    echo "NO NEW VERSION YET :("
  fi
EOF

chmod +x /home/wwwuser1/CRONlook.sh
chown wwwuser1 /home/wwwuser1/CRONlook.sh
chown wwwuser1 /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar
sed -i -e '15i@reboot wwwuser1 java -jar /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar' /etc/crontab
sed -i -e '15i*/1 * * * * wwwuser1 /home/wwwuser1/CRONlook.sh' /etc/crontab
service cron restart
java -jar /home/wwwuser1/frontend-service-0.0.1-SNAPSHOT.jar

